// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerProjectCase5.WebApi.Context;

#nullable disable

namespace SoccerProjectCase5.WebApi.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoccerProjectCase5.WebApi.Entities.Fixture", b =>
                {
                    b.Property<int>("FixtureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FixtureId"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("FullTimeAwayScore")
                        .HasColumnType("int");

                    b.Property<int>("FullTimeHomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HalfTimeAwayScore")
                        .HasColumnType("int");

                    b.Property<int>("HalfTimeHomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StadiumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("FixtureId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("SoccerProjectCase5.WebApi.Entities.MatchEvent", b =>
                {
                    b.Property<int>("MatchEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchEventId"));

                    b.Property<string>("EventDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("MatchEventId");

                    b.HasIndex("FixtureId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("SoccerProjectCase5.WebApi.Entities.MatchStatistic", b =>
                {
                    b.Property<int>("MatchStatisticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchStatisticId"));

                    b.Property<int>("CornersAway")
                        .HasColumnType("int");

                    b.Property<int>("CornersHome")
                        .HasColumnType("int");

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<int>("FoulsAway")
                        .HasColumnType("int");

                    b.Property<int>("FoulsHome")
                        .HasColumnType("int");

                    b.Property<int>("OffsidesAway")
                        .HasColumnType("int");

                    b.Property<int>("OffsidesHome")
                        .HasColumnType("int");

                    b.Property<int>("PassAccuracyAway")
                        .HasColumnType("int");

                    b.Property<int>("PassAccuracyHome")
                        .HasColumnType("int");

                    b.Property<int>("PassesAway")
                        .HasColumnType("int");

                    b.Property<int>("PassesHome")
                        .HasColumnType("int");

                    b.Property<int>("PossessionAway")
                        .HasColumnType("int");

                    b.Property<int>("PossessionHome")
                        .HasColumnType("int");

                    b.Property<int>("RedCardsAway")
                        .HasColumnType("int");

                    b.Property<int>("RedCardsHome")
                        .HasColumnType("int");

                    b.Property<int>("ShotsAway")
                        .HasColumnType("int");

                    b.Property<int>("ShotsHome")
                        .HasColumnType("int");

                    b.Property<int>("ShotsOnTargetAway")
                        .HasColumnType("int");

                    b.Property<int>("ShotsOnTargetHome")
                        .HasColumnType("int");

                    b.Property<int>("YellowCardsAway")
                        .HasColumnType("int");

                    b.Property<int>("YellowCardsHome")
                        .HasColumnType("int");

                    b.HasKey("MatchStatisticId");

                    b.HasIndex("FixtureId")
                        .IsUnique();

                    b.ToTable("MatchStatistics");
                });

            modelBuilder.Entity("SoccerProjectCase5.WebApi.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SoccerProjectCase5.WebApi.Entities.Fixture", b =>
                {
                    b.HasOne("SoccerProjectCase5.WebApi.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoccerProjectCase5.WebApi.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("SoccerProjectCase5.WebApi.Entities.MatchEvent", b =>
                {
                    b.HasOne("SoccerProjectCase5.WebApi.Entities.Fixture", "Fixture")
                        .WithMany("Events")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("SoccerProjectCase5.WebApi.Entities.MatchStatistic", b =>
                {
                    b.HasOne("SoccerProjectCase5.WebApi.Entities.Fixture", "Fixture")
                        .WithOne("Statistic")
                        .HasForeignKey("SoccerProjectCase5.WebApi.Entities.MatchStatistic", "FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("SoccerProjectCase5.WebApi.Entities.Fixture", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Statistic");
                });
#pragma warning restore 612, 618
        }
    }
}
